### PR TITLE
Add TopAPI and attendance api, DingTalkClient.PartnerID

### PR DESCRIPTION
**Pull request by ipandtcp**
NothingChange,
But add: DingTalkClient.PartnerID,
         attendance,
         top API: messages, approvals,
         test files, examples

### CODE REVIEW

**Comment by ipandtcp** [comment]
Happy to commit

**Comment by ipandtcp** [comment]
请问没merge的原因是什么啊？辛苦写的代码啊哥哥

**Comment by hugozhu** [comment]
thanks

**Comment by ipandtcp** [comment]
Thinks but your still not merge it.

**Comment by ipandtcp** [comment]
I have to say i'm SAD for that.

**Comment by hugozhu** [comment]
DONE

**Pull request merged**
